In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder, RobustScaler
from sklearn.metrics import mean_squared_error, r2_score

In [6]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [10]:

df = pd.read_csv("/content/drive/MyDrive/DS&ML/Regression/house_price.csv")
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [12]:
label_encoder=LabelEncoder()
cols = ['mainroad', 'guestroom', 'basement', 'hotwaterheating', 'airconditioning', 'prefarea', 'furnishingstatus']
for col in cols:
  df[col] =label_encoder.fit_transform(df[col])
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,1,0,0,0,1,2,1,0
1,12250000,8960,4,4,4,1,0,0,0,1,3,0,0
2,12250000,9960,3,2,2,1,0,1,0,0,2,1,1
3,12215000,7500,4,2,2,1,0,1,0,1,3,1,0
4,11410000,7420,4,1,2,1,1,1,0,1,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,1,0,1,0,0,2,0,2
541,1767150,2400,3,1,1,0,0,0,0,0,0,0,1
542,1750000,3620,2,1,1,1,0,0,0,0,0,0,2
543,1750000,2910,3,1,1,0,0,0,0,0,0,0,0
544,1750000,3850,3,1,2,1,0,0,0,0,0,0,2

In [13]:
x= df.drop("price", axis=1)
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,1,0,0,0,1,2,1,0
1,12250000,8960,4,4,4,1,0,0,0,1,3,0,0
2,12250000,9960,3,2,2,1,0,1,0,0,2,1,1
3,12215000,7500,4,2,2,1,0,1,0,1,3,1,0
4,11410000,7420,4,1,2,1,1,1,0,1,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,1,0,1,0,0,2,0,2
541,1767150,2400,3,1,1,0,0,0,0,0,0,0,1
542,1750000,3620,2,1,1,1,0,0,0,0,0,0,2
543,1750000,2910,3,1,1,0,0,0,0,0,0,0,0
544,1750000,3850,3,1,2,1,0,0,0,0,0,0,2

In [17]:
y= df["price"]
y

0      13300000
1      12250000
2      12250000
3      12215000
4      11410000
         ...
540     1820000
541     1767150
542     1750000
543     1750000
544     1750000
Name: price, Length: 545, dtype: int64

In [20]:
scaler= RobustScaler()
scaler.fit_transform(x)
x

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,7420,4,2,3,1,0,0,0,1,2,1,0
1,8960,4,4,4,1,0,0,0,1,3,0,0
2,9960,3,2,2,1,0,1,0,0,2,1,1
3,7500,4,2,2,1,0,1,0,1,3,1,0
4,7420,4,1,2,1,1,1,0,1,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
540,3000,2,1,1,1,0,1,0,0,2,0,2
541,2400,3,1,1,0,0,0,0,0,0,0,1
542,3620,2,1,1,1,0,0,0,0,0,0,2
543,2910,3,1,1,0,0,0,0,0,0,0,0
544,3850,3,1,2,1,0,0,0,0,0,0,2

In [21]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2, random_state=40)

In [22]:
model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [23]:
y_pred=model.predict(x_test)
y_pred

array([7154236.434521  , 6473033.12762163, 7967353.36422652,
       3250053.54966785, 5041218.60579335, 2976073.5609929 ,
       4937665.82889841, 3883826.62741168, 6268804.63250383,
       2907287.6074124 , 6460451.13918715, 3286358.39831609,
       3275477.64306413, 3065101.06146753, 7948917.26201536,
       2492806.62448375, 5254217.74779316, 7418086.14841512,
       4264026.94795389, 2729071.62316377, 3403605.75637439,
       3132342.46355616, 3394199.53426822, 5598580.8499631 ,
       2822869.50961042, 2271685.66727903, 4274338.37067981,
       5116740.00667758, 3508335.21544579, 3885646.47445227,
       4251680.67490509, 6440889.92804155, 6927347.98608501,
       3227734.71928694, 6871357.8712789 , 3422524.70343751,
       3390125.08812476, 5617687.34840426, 3919707.55979289,
       2934616.32414117, 5824539.15538491, 4501489.17449829,
       7116285.52783018, 5881343.20169434, 6671920.72585857,
       5159462.03470178, 3285881.50887597, 6621470.53673986,
       6235750.13830625, 5020718.43252712, 7235607.53317664,
       4148156.57057791, 4264713.84448708, 6569231.46931377,
       7619862.59386692, 6193874.08470961, 6486008.11543779,
       4845753.94053638, 4754743.46790423, 3767226.22950693,
       5182078.25635305, 4829580.5951507 , 6769485.40173534,
       4018436.62530435, 2729071.62316377, 3542640.05627738,
       2939562.69774919, 3194035.04501523, 3003404.00755869,
       5710349.2866826 , 4994106.23460807, 5020326.97341331,
       3997552.24545037, 4747791.07594997, 5925526.2610697 ,
       4471813.57025994, 5699992.68783349, 5283199.83299246,
       4814814.91473679, 5705731.87747448, 4602450.53671511,
       4800817.877962  , 5110752.32017399, 3717331.05969102,
       4119245.39281307, 5069076.48833354, 5468560.26844334,
       3862060.82571295, 5418133.6164386 , 6526357.74747326,
       3667061.87429705, 5587481.60668658, 4248651.11696385,
       5371363.19681995, 5830673.74700749, 5943253.69971591,
       3335267.55988302, 4582275.87793191, 2749874.79154361,
       7019273.54075826, 3907780.36938549, 7246505.49757983,
       3589821.30776998, 4374808.82899143, 2197277.91071363,
       5741390.60282661, 4291863.84101623, 2989360.75805321,
       8195393.98998921])

In [24]:
coef=model.coef_
intercept=model.intercept_

In [25]:
mse=mean_squared_error(y_test,y_pred)
rootmse=np.sqrt(mse)
r2=r2_score(y_test,y_pred)

In [26]:
print("mean squared error",mse)
print("root mean squred error",rootmse)
print("R squared-R2",r2)

mean squared error 1466037860959.4463
root mean squred error 1210800.5041952396
R squared-R2 0.6591408850872555